<?php

namespace App\Services\Instagram;

class NetscapeCookieFormatter
{
    /**
     * @param  array<int, array{domain: string, path?: string, secure?: bool, expires?: int, name: string, value: string}>  $cookies
     */
    public function format(array $cookies): string
    {
        $lines = [
            '# Netscape HTTP Cookie File',
            '# Generated by n0glemand. Do not edit.',
            '',
        ];

        foreach ($cookies as $cookie) {
            $domain = (string) $cookie['domain'];
            $path = (string) ($cookie['path'] ?? '/');
            $secure = (bool) ($cookie['secure'] ?? true);
            $expires = (int) ($cookie['expires'] ?? 0);
            $name = (string) $cookie['name'];
            $value = (string) $cookie['value'];

            if ($name === '' || $domain === '') {
                continue;
            }

            $lines[] = implode("\t", [
                $domain,
                str_starts_with($domain, '.') ? 'TRUE' : 'FALSE',
                $path,
                $secure ? 'TRUE' : 'FALSE',
                (string) $expires,
                $name,
                $value,
            ]);
        }

        return implode("\n", $lines)."\n";
    }
}
